# https://taskfile.dev

version: "3"

tasks:
  install-binaryen:
    status:
      - which wasm-opt
    cmds:
      - wget https://github.com/WebAssembly/binaryen/releases/download/version_108/binaryen-version_108-x86_64-linux.tar.gz
      - tar -xf binaryen-version_108-x86_64-linux.tar.gz
      - rm binaryen-version_108-x86_64-linux.tar.gz
      - mv binaryen-version_108/bin/* ~/.local/bin
      - rm -rf binaryen-version_108
      - wasm-opt --version

  build-frontend:
    env:
      GOOS: js
      GOARCH: wasm
      GOROOT:
        sh: go env GOROOT
    cmds:
      - mkdir -p public
      - cp ./frontend/* ./public/
      - cp "$GOROOT/misc/wasm/wasm_exec.js" ./public/wasm_exec.js
      - go build -o public/frontend.wasm ./wasm/

  optimize-wasm:
    deps:
      - install-binaryen
    cmds:
      - wasm-opt -Oz -o public/frontend.wasm public/frontend.wasm

  build-server:
    cmds:
      - go build -o server.bin ./server/

  build:
    cmds:
      - task: build-frontend
      - task: optimize-wasm
      - task: build-server

  run:
    deps:
      - build
    cmds:
      - ./server.bin
